### ISSUE TITLE
No se debe permitir ingresar números negativos en las entrevistas.

### ISSUE THREAD

**Issue by andreshg112** [MinTIC/apps.co#10]
**Estoy reportando un/una ...**  (Marca uno con una "x")

```
[x] reporte de un bug
[ ] nueva funcionalidad en la plataforma
[ ] Idea o sugerencia
```

**Describe tu reporte**

...

Además del número negativo en las entrevistas, el cuadro de la imagen está detrás de los botones.
![appsco](https://cloud.githubusercontent.com/assets/15859884/17640462/8b7461ae-60c5-11e6-8287-c711030e813e.JPG)

**Comment by sanfeijoo** [comment]
Gracias por reporte el problema, vamos a realizar los ajustes. Gracias

**Comment by PabloVallejo** [comment]
Hola @andreshg112 realizamos los ajustes en la plataforma, ahora las entrevistas van de uno en adelante.
