### ISSUE TITLE
Incomodo selector de fecha de nacimiento 

### ISSUE THREAD

**Issue by davidcastillo** [MinTIC/apps.co#11]
**Estoy reportando un/una ...**  (Marca uno con una "x")

```
[ ] reporte de un bug
[ ] nueva funcionalidad en la plataforma
[X] Idea o sugerencia
```

**Describe tu reporte**

...
El selector de la fecha de nacimiento tiene CERO en usabilidad, tengo que dar 60.000 clicks para llegar mi fecha de nacimiento en Oct de 1986,  toca desplazarse mes por mes es demasiado incomodo

Seria chevere que lo arreglaran

Gracias

**Comment by camilonova** [comment]
Muchas gracias por tu reporte, vamos a tenerlo en cuenta.

**Comment by sanfeijoo** [comment]
Hola David, al selector de fecha se agregaron botones en el mes y año, así puede seleccionar el mes y año y no navegar por cada mes.
