### ISSUE TITLE
Sugerencia del EMAIL en DATOS DE CONTACTO.

### ISSUE THREAD

**Issue by andreshg112** [MinTIC/apps.co#12]
**Estoy reportando un/una ...**  (Marca uno con una "x")

```
[ ] reporte de un bug
[ ] nueva funcionalidad en la plataforma
[x] Idea o sugerencia
```

**Describe tu reporte**

...

En el perfil de los emprendimientos, en la parte donde dice DATOS DE CONTACTO, en el botón de EMAIL, no está enlazado al email del emprendimiento, sino al del líder del emprendimiento.

**Comment by felipe3dfx** [comment]
realizado
