### ISSUE TITLE
Definir "guidelines" para crear issues

### ISSUE THREAD

**Issue by UnJavaScripter** [MinTIC/apps.co#4]
Con el fin de estandarizar los issues y hacer más fácil su clasificación, [algo así como esto](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-submitting-an-issue). En particular definir estructura del titulo y posibles soluciones dentro del issue

**Comment by camilonova** [comment]
Que le cambiarías al que ya existe? https://github.com/MinTIC/apps.co/blob/master/.github/ISSUE_TEMPLATE.md

**Comment by UnJavaScripter** [comment]
No todos los _issues_ son problemas con la plataforma, como hemos visto hasta ahora con los 3 primeros issues estos pueden ser ideas o sugerencias, por lo tanto no estarían ligados a un navegador o sistema operativo.

En cuánto a los títulos, tener algo así como [docs] Agregar un archivo CONTRIBUTING.MD o [UI] Pintar todo de color salmon, [PERF] Remover listeners a elementos del DOM cuando...

De esa forma es más fácil clasificarlos y asignar _owners_ si fuera el caso.

Sugerir una sección de _issues relacionados_ dentro del cuerpo del issue puede ayudar a evitar reportes repetidos, ya que se motiva al desarrollador que hace un reporte a verificar si alguien ya ha hablado de un tema similar.

_Suggested fix_ daría al desarrollador la oportunidad de proponer soluciones más que sólo indicar qué está mal.

_Reproducir el error_ ayudaría al owner del issue a tener una mejor perspectiva de lo que sucede. La persona que reporta ayudaría a aislar el inconveniente mostrando un ejemplo en jsfiddle, plnkr...

**Comment by PabloVallejo** [comment]
Pienso que podríamos empezar con etiquetas para los Issues, propongo estás:

* `Idea`
* `Bug`
* `Mejora`

**Comment by PabloVallejo** [comment]
Ver también: 6aac28af75180b8d230c81753037aea013af3237
