### ISSUE TITLE
No debería llegar notificación de una actividad que uno mismo realiza.

### ISSUE THREAD

**Issue by andreshg112** [MinTIC/apps.co#5]
**Estoy reportando un/una ...**  (Marca uno con una "x")
- [ ] reporte de un bug
- [ ] nueva funcionalidad en la plataforma
- [x] Idea o sugerencia

**Describe tu reporte**

...

Cuando alguien realiza una actividad dentro de la plataforma, por ejemplo, crear una hipótesis o cambiar el estado de una tarea, a esa misma persona le llega una notificación de que realizó esa tarea.
Considero que tiene poco sentido que uno sea notificado de lo que uno mismo acaba de hacer.

**Comment by camilonova** [comment]
Gracias por el reporte, vamos a analizarlo.

**Comment by PabloVallejo** [comment]
Hola @andreshg112 realizamos el cambio en la plataforma, ya no recibirás notificaciones de tus propias acciones.
