### ISSUE TITLE
Permitir la edición y eliminación de las entrevistas

### ISSUE THREAD

**Issue by andreshg112** [MinTIC/apps.co#6]
**Estoy reportando un/una ...**  (Marca uno con una "x")
- [ ] reporte de un bug
- [ ] nueva funcionalidad en la plataforma
- [x] Idea o sugerencia

**Describe tu reporte**

...

La plataforma debería permitir cambiar el archivo de las entrevistas. Iba a subir una entrevista, olvidé escribir la cantidad de entrevistas, y luego se quitó el archivo cargado, pensé que estaba en memoria. Ahora, no me permite eliminar la entrevista para subirla con la foto respectiva.

**Comment by camilonova** [comment]
Gracias
