### ISSUE TITLE
Los emprendedores no deberían poder cambiar la descripción de las tareas que le sean asignadas

### ISSUE THREAD

**Issue by andreshg112** [MinTIC/apps.co#7]
**Estoy reportando un/una ...**  (Marca uno con una "x")
- [ ] nueva funcionalidad en la plataforma
- [x] Idea o sugerencia
- [ ] reporte de un bug

**Describe tu reporte**

...

Considero que los emprendedores no deberían poder cambiar la descripción de las tareas que los mentores le asignen. Si a uno le asignan una tarea, ¿por qué uno tendría la facultad de cambiar la descripción?

**Comment by felipe3dfx** [comment]
Gracias por la sugerencia, lo tendremos en cuenta.

**Comment by PabloVallejo** [comment]
@andreshg112 realizamos el cambio en la plataforma, ahora las personas asignadas no pueden cambiar la descripción de las hipótesis.
