### ISSUE TITLE
El Dashboard no cuenta las hipótesis no validadas.

### ISSUE THREAD

**Issue by andreshg112** [MinTIC/apps.co#9]
**Estoy reportando un/una ...**  (Marca uno con una "x")

```
[x] reporte de un bug
[ ] nueva funcionalidad en la plataforma
[ ] Idea o sugerencia
```

**Describe tu reporte**

...

Tenemos 4 hipótesis no validadas pero no las muestra en el dashboard.
![appsco hipotesis](https://cloud.githubusercontent.com/assets/15859884/17640447/5f20531a-60c5-11e6-92fc-e7704e5831b4.JPG)

**Comment by sanfeijoo** [comment]
Gracias por el reporte, vamos a revisar que el funcionamiento este bien.

**Comment by sanfeijoo** [comment]
@andreshg112 , ya esta funcionan el contador.
